// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cards_list.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cards_5flist_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cards_5flist_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "card.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cards_5flist_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cards_5flist_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cards_5flist_2eproto;
namespace protos {
class CardsListProto;
struct CardsListProtoDefaultTypeInternal;
extern CardsListProtoDefaultTypeInternal _CardsListProto_default_instance_;
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> ::protos::CardsListProto* Arena::CreateMaybeMessage<::protos::CardsListProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protos {

// ===================================================================

class CardsListProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.CardsListProto) */ {
 public:
  inline CardsListProto() : CardsListProto(nullptr) {}
  ~CardsListProto() override;
  explicit PROTOBUF_CONSTEXPR CardsListProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CardsListProto(const CardsListProto& from);
  CardsListProto(CardsListProto&& from) noexcept
    : CardsListProto() {
    *this = ::std::move(from);
  }

  inline CardsListProto& operator=(const CardsListProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline CardsListProto& operator=(CardsListProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CardsListProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const CardsListProto* internal_default_instance() {
    return reinterpret_cast<const CardsListProto*>(
               &_CardsListProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CardsListProto& a, CardsListProto& b) {
    a.Swap(&b);
  }
  inline void Swap(CardsListProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CardsListProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CardsListProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CardsListProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CardsListProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CardsListProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CardsListProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.CardsListProto";
  }
  protected:
  explicit CardsListProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCardFieldNumber = 1,
  };
  // repeated .protos.CardProto card = 1;
  int card_size() const;
  private:
  int _internal_card_size() const;
  public:
  void clear_card();
  ::protos::CardProto* mutable_card(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::CardProto >*
      mutable_card();
  private:
  const ::protos::CardProto& _internal_card(int index) const;
  ::protos::CardProto* _internal_add_card();
  public:
  const ::protos::CardProto& card(int index) const;
  ::protos::CardProto* add_card();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::CardProto >&
      card() const;

  // @@protoc_insertion_point(class_scope:protos.CardsListProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::CardProto > card_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cards_5flist_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CardsListProto

// repeated .protos.CardProto card = 1;
inline int CardsListProto::_internal_card_size() const {
  return _impl_.card_.size();
}
inline int CardsListProto::card_size() const {
  return _internal_card_size();
}
inline ::protos::CardProto* CardsListProto::mutable_card(int index) {
  // @@protoc_insertion_point(field_mutable:protos.CardsListProto.card)
  return _impl_.card_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::CardProto >*
CardsListProto::mutable_card() {
  // @@protoc_insertion_point(field_mutable_list:protos.CardsListProto.card)
  return &_impl_.card_;
}
inline const ::protos::CardProto& CardsListProto::_internal_card(int index) const {
  return _impl_.card_.Get(index);
}
inline const ::protos::CardProto& CardsListProto::card(int index) const {
  // @@protoc_insertion_point(field_get:protos.CardsListProto.card)
  return _internal_card(index);
}
inline ::protos::CardProto* CardsListProto::_internal_add_card() {
  return _impl_.card_.Add();
}
inline ::protos::CardProto* CardsListProto::add_card() {
  ::protos::CardProto* _add = _internal_add_card();
  // @@protoc_insertion_point(field_add:protos.CardsListProto.card)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::CardProto >&
CardsListProto::card() const {
  // @@protoc_insertion_point(field_list:protos.CardsListProto.card)
  return _impl_.card_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cards_5flist_2eproto
