// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_room_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_room_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "player.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_room_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_room_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_room_2eproto;
namespace protos {
class RoomProto;
struct RoomProtoDefaultTypeInternal;
extern RoomProtoDefaultTypeInternal _RoomProto_default_instance_;
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> ::protos::RoomProto* Arena::CreateMaybeMessage<::protos::RoomProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protos {

// ===================================================================

class RoomProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.RoomProto) */ {
 public:
  inline RoomProto() : RoomProto(nullptr) {}
  ~RoomProto() override;
  explicit PROTOBUF_CONSTEXPR RoomProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoomProto(const RoomProto& from);
  RoomProto(RoomProto&& from) noexcept
    : RoomProto() {
    *this = ::std::move(from);
  }

  inline RoomProto& operator=(const RoomProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomProto& operator=(RoomProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoomProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoomProto* internal_default_instance() {
    return reinterpret_cast<const RoomProto*>(
               &_RoomProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoomProto& a, RoomProto& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoomProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoomProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoomProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoomProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoomProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.RoomProto";
  }
  protected:
  explicit RoomProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 4,
    kNameFieldNumber = 2,
    kIdFieldNumber = 1,
    kNbMaxPlayersFieldNumber = 3,
  };
  // repeated .protos.PlayerProto player = 4;
  int player_size() const;
  private:
  int _internal_player_size() const;
  public:
  void clear_player();
  ::protos::PlayerProto* mutable_player(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::PlayerProto >*
      mutable_player();
  private:
  const ::protos::PlayerProto& _internal_player(int index) const;
  ::protos::PlayerProto* _internal_add_player();
  public:
  const ::protos::PlayerProto& player(int index) const;
  ::protos::PlayerProto* add_player();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::PlayerProto >&
      player() const;

  // optional string name = 2;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // required int32 id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // optional int32 nb_max_players = 3;
  bool has_nb_max_players() const;
  private:
  bool _internal_has_nb_max_players() const;
  public:
  void clear_nb_max_players();
  int32_t nb_max_players() const;
  void set_nb_max_players(int32_t value);
  private:
  int32_t _internal_nb_max_players() const;
  void _internal_set_nb_max_players(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protos.RoomProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::PlayerProto > player_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t id_;
    int32_t nb_max_players_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoomProto

// required int32 id = 1;
inline bool RoomProto::_internal_has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RoomProto::has_id() const {
  return _internal_has_id();
}
inline void RoomProto::clear_id() {
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t RoomProto::_internal_id() const {
  return _impl_.id_;
}
inline int32_t RoomProto::id() const {
  // @@protoc_insertion_point(field_get:protos.RoomProto.id)
  return _internal_id();
}
inline void RoomProto::_internal_set_id(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.id_ = value;
}
inline void RoomProto::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protos.RoomProto.id)
}

// optional string name = 2;
inline bool RoomProto::_internal_has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoomProto::has_name() const {
  return _internal_has_name();
}
inline void RoomProto::clear_name() {
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RoomProto::name() const {
  // @@protoc_insertion_point(field_get:protos.RoomProto.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoomProto::set_name(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protos.RoomProto.name)
}
inline std::string* RoomProto::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:protos.RoomProto.name)
  return _s;
}
inline const std::string& RoomProto::_internal_name() const {
  return _impl_.name_.Get();
}
inline void RoomProto::_internal_set_name(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* RoomProto::_internal_mutable_name() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* RoomProto::release_name() {
  // @@protoc_insertion_point(field_release:protos.RoomProto.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.name_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void RoomProto::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protos.RoomProto.name)
}

// optional int32 nb_max_players = 3;
inline bool RoomProto::_internal_has_nb_max_players() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RoomProto::has_nb_max_players() const {
  return _internal_has_nb_max_players();
}
inline void RoomProto::clear_nb_max_players() {
  _impl_.nb_max_players_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int32_t RoomProto::_internal_nb_max_players() const {
  return _impl_.nb_max_players_;
}
inline int32_t RoomProto::nb_max_players() const {
  // @@protoc_insertion_point(field_get:protos.RoomProto.nb_max_players)
  return _internal_nb_max_players();
}
inline void RoomProto::_internal_set_nb_max_players(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.nb_max_players_ = value;
}
inline void RoomProto::set_nb_max_players(int32_t value) {
  _internal_set_nb_max_players(value);
  // @@protoc_insertion_point(field_set:protos.RoomProto.nb_max_players)
}

// repeated .protos.PlayerProto player = 4;
inline int RoomProto::_internal_player_size() const {
  return _impl_.player_.size();
}
inline int RoomProto::player_size() const {
  return _internal_player_size();
}
inline ::protos::PlayerProto* RoomProto::mutable_player(int index) {
  // @@protoc_insertion_point(field_mutable:protos.RoomProto.player)
  return _impl_.player_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::PlayerProto >*
RoomProto::mutable_player() {
  // @@protoc_insertion_point(field_mutable_list:protos.RoomProto.player)
  return &_impl_.player_;
}
inline const ::protos::PlayerProto& RoomProto::_internal_player(int index) const {
  return _impl_.player_.Get(index);
}
inline const ::protos::PlayerProto& RoomProto::player(int index) const {
  // @@protoc_insertion_point(field_get:protos.RoomProto.player)
  return _internal_player(index);
}
inline ::protos::PlayerProto* RoomProto::_internal_add_player() {
  return _impl_.player_.Add();
}
inline ::protos::PlayerProto* RoomProto::add_player() {
  ::protos::PlayerProto* _add = _internal_add_player();
  // @@protoc_insertion_point(field_add:protos.RoomProto.player)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::PlayerProto >&
RoomProto::player() const {
  // @@protoc_insertion_point(field_list:protos.RoomProto.player)
  return _impl_.player_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_room_2eproto
